disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length: 160
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
